=== VanCristi/RTEConfig/tests/TRS.RTECONFIG.BUGFIX/xsd/ConfigPSA_NvM.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!-- edited with XMLSpy v2006 rel. 3 U (http://www.altova.com) by PSA (PSA / PCA PEUGEOT CITROEN) -->
<!--W3C Schema generated by XMLSpy v2006 rel. 3 U (http://www.altova.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="BLOCK" type="BLOCKType"/>
	<xs:element name="CONFIG_PSA_NVM">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="BLOCKS" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="BLOCK" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="PROFILS" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="PROFILE" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="MAPPINGS" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="MAPPING" type="MAPPINGType" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="NVM_COMPILED_CONFIG_ID" type="xs:unsignedShort" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="REF">
		<xs:annotation>
			<xs:documentation/>
		</xs:annotation>
		<xs:simpleContent>
			<xs:extension base="REF--SIMPLE"/>
		</xs:simpleContent>
	</xs:complexType>
	<xs:simpleType name="REF--SIMPLE">
		<xs:restriction base="xs:string">
			<xs:pattern value="/?[a-zA-Z][a-zA-Z0-9_]{0,127}(/[a-zA-Z][a-zA-Z0-9_]{0,127})*"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="INTERFACE-TYPE-ENUM">
		<xs:restriction base="xs:string">
			<xs:enumeration value="SENDER-RECEIVER-INTERFACE"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="MANAGEMENT-TYPE-ENUM">
		<xs:restriction base="xs:string">
			<xs:enumeration value="EXPLICIT"/>
			<xs:enumeration value="IMPLICIT"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="DURABILITY-TYPE-ENUM">
		<xs:restriction base="xs:string">
			<xs:enumeration value="LONG_TERM"/>
			<xs:enumeration value="SHORT_TERM"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="DEVICE-TYPE-ENUM">
		<xs:restriction base="xs:string">
			<xs:enumeration value="FEE"/>
			<xs:enumeration value="EA"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="BLOCKType">
		<xs:sequence>
			<xs:element name="SHORT-NAME" type="xs:string"/>
			<xs:element name="TYPE" type="xs:string"/>
			<xs:element name="PROFIL-REF" type="xs:string"/>
			<xs:element name="WRITE-TIMEOUT" minOccurs="0"/>
			<xs:element name="RESPECT-MAPPING" type="xs:boolean" minOccurs="0"/>
			<xs:element name="SDF" type="xs:boolean" minOccurs="0"/>
			<xs:element name="SENDER-RECEIVER-INTERFACE-REFS">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="SENDER-RECEIVER-INTERFACE" maxOccurs="unbounded">
							<xs:complexType>
								<xs:simpleContent>
									<xs:extension base="REF">
										<xs:attribute name="DEST" type="INTERFACE-TYPE-ENUM" use="required"/>
									</xs:extension>
								</xs:simpleContent>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="PROFILE" type="PROFILEType"/>
	<xs:complexType name="PROFILEType">
		<xs:sequence>
			<xs:element name="SHORT-NAME" type="xs:string"/>
			<xs:element name="MANAGEMENT" type="MANAGEMENT-TYPE-ENUM"/>
			<xs:element name="DURABILITY" type="DURABILITY-TYPE-ENUM"/>
			<xs:element name="BLOCK-SIZE-MAX" type="xs:integer"/>
			<xs:element name="SAFETY" type="xs:boolean"/>
			<xs:element name="DEVICE" type="DEVICE-TYPE-ENUM"/>
			<xs:element name="WRITING-NUMBER" type="xs:integer"/>
			<xs:element name="PARAMS">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="PARAM" maxOccurs="unbounded">
							<xs:complexType>
								<xs:simpleContent>
									<xs:extension base="xs:string">
										<xs:attribute name="DEST" use="required"/>
									</xs:extension>
								</xs:simpleContent>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="MAPPINGType">
		<xs:sequence>
			<xs:element name="BLOCK-REF" type="xs:string"/>
			<xs:element name="POSITION" type="xs:unsignedInt"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== VanCristi/RTEConfig/tests/TRS.RTECONFIG.BUGFIX/in/Profiles_cleaned.xml
<CONFIG_PSA_NVM xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation=".\ConfigPSA_NvM.xsd">
	<PROFILS>
		<PROFILE>
			<SHORT-NAME>CfgVh_1</SHORT-NAME>
			<MANAGEMENT>EXPLICIT</MANAGEMENT>
			<DURABILITY>LONG_TERM</DURABILITY>
			<BLOCK-SIZE-MAX>100</BLOCK-SIZE-MAX>
			<SAFETY>true</SAFETY>
			<DEVICE>FEE</DEVICE>
			<WRITING-NUMBER>1500</WRITING-NUMBER>
			<PARAMS>
				<PARAM DEST="NvMBlockJobPriority">0</PARAM>
				<PARAM DEST="NvMBlockCrcType">NVM_CRC16</PARAM>
				<PARAM DEST="NvMBlockManagementType">NVM_BLOCK_REDUNDANT</PARAM>
				<PARAM DEST="NvMRedundantRecovery">NVM_RECOVERY_ON_REQUEST</PARAM>
				<PARAM DEST="NvMBlockUseAutoValidation">False</PARAM>
				<PARAM DEST="NvMBlockUseCRCCompMechanism">False</PARAM>
				<PARAM DEST="NvMBlockUseSetRamBlockStatus">True</PARAM>
				<PARAM DEST="NvMBlockUseSyncMechanism">True</PARAM>
				<PARAM DEST="NvMBlockWriteProt">False</PARAM>
				<PARAM DEST="NvMBswMBlockStatusInformation">False</PARAM>
				<PARAM DEST="NvMCalcRamBlockCrc">True</PARAM>
				<PARAM DEST="NvMInitBlockCallback">False</PARAM>
				<PARAM DEST="NvMMaxNumOfReadRetries">3</PARAM>
				<PARAM DEST="NvMMaxNumOfWriteRetries">3</PARAM>
				<PARAM DEST="NvMNvBlockNum">2</PARAM>
				<PARAM DEST="NvMResistantToChangedSw">False</PARAM>
				<PARAM DEST="NvMRomBlockNum">2</PARAM>
				<PARAM DEST="NvMSelectBlockForReadAll">True</PARAM>
				<PARAM DEST="NvMSelectBlockForWriteAll">False</PARAM>
				<PARAM DEST="NvMStaticBlockIDCheck">True</PARAM>
				<PARAM DEST="NvMWriteBlockOnce">False</PARAM>
				<PARAM DEST="NvMWriteVerification">True</PARAM>
				<PARAM DEST="NvMWriteVerificationDataSize">4</PARAM>	
			</PARAMS>
		</PROFILE>
		<PROFILE>
			<SHORT-NAME>CfgVh_2</SHORT-NAME>
			<MANAGEMENT>EXPLICIT</MANAGEMENT>
			<DURABILITY>LONG_TERM</DURABILITY>
			<BLOCK-SIZE-MAX>100</BLOCK-SIZE-MAX>
			<SAFETY>true</SAFETY>
			<DEVICE>FEE</DEVICE>
			<WRITING-NUMBER>1500</WRITING-NUMBER>
			<PARAMS>
				<PARAM DEST="NvMBlockJobPriority">0</PARAM>
				<PARAM DEST="NvMBlockCrcType">NVM_CRC16</PARAM>
				<PARAM DEST="NvMBlockManagementType">NVM_BLOCK_REDUNDANT</PARAM>
				<PARAM DEST="NvMRedundantRecovery">NVM_RECOVERY_ON_REQUEST</PARAM>
				<PARAM DEST="NvMBlockUseAutoValidation">False</PARAM>
				<PARAM DEST="NvMBlockUseCRCCompMechanism">False</PARAM>
				<PARAM DEST="NvMBlockUseCrc">True</PARAM>
				<PARAM DEST="NvMBlockUseSetRamBlockStatus">False</PARAM>
				<PARAM DEST="NvMBlockUseSyncMechanism">True</PARAM>
				<PARAM DEST="NvMBlockWriteProt">False</PARAM>
				<PARAM DEST="NvMBswMBlockStatusInformation">False</PARAM>
				<PARAM DEST="NvMCalcRamBlockCrc">True</PARAM>
				<PARAM DEST="NvMInitBlockCallback">False</PARAM>
				<PARAM DEST="NvMMaxNumOfReadRetries">3</PARAM>
				<PARAM DEST="NvMMaxNumOfWriteRetries">3</PARAM>
				<PARAM DEST="NvMNvBlockNum">2</PARAM>
				<PARAM DEST="NvMResistantToChangedSw">True</PARAM>
				<PARAM DEST="NvMRomBlockNum">2</PARAM>
				<PARAM DEST="NvMSelectBlockForReadAll">True</PARAM>
				<PARAM DEST="NvMSelectBlockForWriteAll">False</PARAM>
				<PARAM DEST="NvMStaticBlockIDCheck">True</PARAM>
				<PARAM DEST="NvMWriteBlockOnce">False</PARAM>
				<PARAM DEST="NvMWriteVerification">True</PARAM>
			</PARAMS>
		</PROFILE>
		<PROFILE>
			<SHORT-NAME>App_Ram_Implicit</SHORT-NAME>
			<MANAGEMENT>IMPLICIT</MANAGEMENT>
			<DURABILITY>SHORT_TERM</DURABILITY>
			<BLOCK-SIZE-MAX>10</BLOCK-SIZE-MAX>
			<SAFETY>true</SAFETY>
			<DEVICE>FEE</DEVICE>
			<WRITING-NUMBER>1500</WRITING-NUMBER>
			<PARAMS>
				<PARAM DEST="NvMBlockJobPriority">3</PARAM>
				<PARAM DEST="NvMBlockCrcType">NVM_CRC16</PARAM>
				<PARAM DEST="NvMBlockManagementType">NVM_BLOCK_NATIVE</PARAM>
				<PARAM DEST="NvMRedundantRecovery">NVM_AUTOMATIC_RECOVERY</PARAM>
				<PARAM DEST="NvMBlockUseAutoValidation">False</PARAM>
				<PARAM DEST="NvMBlockUseCRCCompMechanism">False</PARAM>
				<PARAM DEST="NvMBlockUseCrc">True</PARAM>
				<PARAM DEST="NvMBlockUseSetRamBlockStatus">True</PARAM>
				<PARAM DEST="NvMBlockUseSyncMechanism">True</PARAM>
				<PARAM DEST="NvMBlockWriteProt">True</PARAM>
				<PARAM DEST="NvMBswMBlockStatusInformation">False</PARAM>
				<PARAM DEST="NvMCalcRamBlockCrc">True</PARAM>
				<PARAM DEST="NvMInitBlockCallback">False</PARAM>
				<PARAM DEST="NvMMaxNumOfReadRetries">0</PARAM>
				<PARAM DEST="NvMMaxNumOfWriteRetries">0</PARAM>
				<PARAM DEST="NvMNvBlockNum">1</PARAM>
				<PARAM DEST="NvMResistantToChangedSw">False</PARAM>
				<PARAM DEST="NvMRomBlockNum">1</PARAM>
				<PARAM DEST="NvMSelectBlockForReadAll">True</PARAM>
				<PARAM DEST="NvMSelectBlockForWriteAll">False</PARAM>
				<PARAM DEST="NvMStaticBlockIDCheck">True</PARAM>
				<PARAM DEST="NvMWriteBlockOnce">True</PARAM>
				<PARAM DEST="NvMWriteVerification">False</PARAM>
				<PARAM DEST="NvMWriteVerificationDataSize">4</PARAM>
			</PARAMS>
		</PROFILE>
		<PROFILE>
			<SHORT-NAME>App_Eep_Explicit_1</SHORT-NAME>
			<MANAGEMENT>EXPLICIT</MANAGEMENT>
			<DURABILITY>LONG_TERM</DURABILITY>
			<BLOCK-SIZE-MAX>100</BLOCK-SIZE-MAX>
			<SAFETY>true</SAFETY>
			<DEVICE>FEE</DEVICE>
			<WRITING-NUMBER>200000</WRITING-NUMBER>
			<PARAMS>
				<PARAM DEST="NvMBlockJobPriority">3</PARAM>
				<PARAM DEST="NvMBlockCrcType">NVM_CRC16</PARAM>
				<PARAM DEST="NvMBlockManagementType">NVM_BLOCK_NATIVE</PARAM>
				<PARAM DEST="NvMRedundantRecovery">NVM_RECOVERY_ON_REQUEST</PARAM>
				<PARAM DEST="NvMBlockUseAutoValidation">False</PARAM>
				<PARAM DEST="NvMBlockUseCRCCompMechanism">False</PARAM>
				<PARAM DEST="NvMBlockUseCrc">True</PARAM>
				<PARAM DEST="NvMBlockUseSetRamBlockStatus">False</PARAM>
				<PARAM DEST="NvMBlockUseSyncMechanism">True</PARAM>
				<PARAM DEST="NvMBlockWriteProt">False</PARAM>
				<PARAM DEST="NvMBswMBlockStatusInformation">False</PARAM>
				<PARAM DEST="NvMCalcRamBlockCrc">True</PARAM>
				<PARAM DEST="NvMInitBlockCallback">False</PARAM>
				<PARAM DEST="NvMMaxNumOfReadRetries">2</PARAM>
				<PARAM DEST="NvMMaxNumOfWriteRetries">1</PARAM>
				<PARAM DEST="NvMNvBlockNum">1</PARAM>
				<PARAM DEST="NvMResistantToChangedSw">False</PARAM>
				<PARAM DEST="NvMRomBlockNum">1</PARAM>
				<PARAM DEST="NvMSelectBlockForReadAll">True</PARAM>
				<PARAM DEST="NvMSelectBlockForWriteAll">True</PARAM>
				<PARAM DEST="NvMStaticBlockIDCheck">True</PARAM>
				<PARAM DEST="NvMWriteBlockOnce">False</PARAM>
				<PARAM DEST="NvMWriteVerification">True</PARAM>
				<PARAM DEST="NvMWriteVerificationDataSize">4</PARAM>
			</PARAMS>
		</PROFILE>
		<PROFILE>
			<SHORT-NAME>App_Eep_Explicit_2</SHORT-NAME>
			<MANAGEMENT>EXPLICIT</MANAGEMENT>
			<DURABILITY>LONG_TERM</DURABILITY>
			<BLOCK-SIZE-MAX>100</BLOCK-SIZE-MAX>
			<SAFETY>true</SAFETY>
			<DEVICE>FEE</DEVICE>
			<WRITING-NUMBER>200000</WRITING-NUMBER>
			<PARAMS>
				<PARAM DEST="NvMBlockJobPriority">2</PARAM>
				<PARAM DEST="NvMBlockCrcType">NVM_CRC16</PARAM>
				<PARAM DEST="NvMBlockManagementType">NVM_BLOCK_REDUNDANT</PARAM>
				<PARAM DEST="NvMRedundantRecovery">NVM_RECOVERY_ON_REQUEST</PARAM>
				<PARAM DEST="NvMBlockUseAutoValidation">False</PARAM>
				<PARAM DEST="NvMBlockUseCRCCompMechanism">False</PARAM>
				<PARAM DEST="NvMBlockUseCrc">True</PARAM>
				<PARAM DEST="NvMBlockUseSetRamBlockStatus">False</PARAM>
				<PARAM DEST="NvMBlockUseSyncMechanism">True</PARAM>
				<PARAM DEST="NvMBlockWriteProt">False</PARAM>
				<PARAM DEST="NvMBswMBlockStatusInformation">False</PARAM>
				<PARAM DEST="NvMCalcRamBlockCrc">True</PARAM>
				<PARAM DEST="NvMInitBlockCallback">False</PARAM>
				<PARAM DEST="NvMMaxNumOfReadRetries">2</PARAM>
				<PARAM DEST="NvMMaxNumOfWriteRetries">3</PARAM>
				<PARAM DEST="NvMNvBlockNum">2</PARAM>
				<PARAM DEST="NvMResistantToChangedSw">True</PARAM>
				<PARAM DEST="NvMRomBlockNum">2</PARAM>
				<PARAM DEST="NvMSelectBlockForReadAll">True</PARAM>
				<PARAM DEST="NvMSelectBlockForWriteAll">True</PARAM>
				<PARAM DEST="NvMStaticBlockIDCheck">True</PARAM>
				<PARAM DEST="NvMWriteBlockOnce">False</PARAM>
				<PARAM DEST="NvMWriteVerification">True</PARAM>
				<PARAM DEST="NvMWriteVerificationDataSize">4</PARAM>
			</PARAMS>
		</PROFILE>
	</PROFILS>
</CONFIG_PSA_NVM>
